application: organic-kitchen
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: main.wsgi.application

builtins:
- django_wsgi: on

libraries:
- name: django
  version: 1.5
- name: MySQLdb
  version: "latest"
- name: ssl
  version: latest
